// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

TABLE clients{
  client_id INT [primary key]
  name_client VARCHAR(50)
  INN VARCHAR(12)
}

TABLE payments_code{
  code_id INT [primary key]
  code_name VARCHAR(20)
  code_description VARCHAR(100)
  category VARCHAR(10) 
}

TABLE payments{
  payment_id INT [primary key]
  client_id INT
  code_id INT 
  amount DECIMAL(10, 2)
  time_payment TIMESTAMP
  blocked BOOLEAN
}
TABLE block_history{
  history_id INT [primary key]
  client_id INT
  action VARCHAR(10)                
  code_id INT               
  initiated_by VARCHAR(100)         
  initiated_at TIMESTAMP                                  
}

REF: clients.client_id < block_history.client_id
REF: payments_code.code_id < block_history.code_id
REF: clients.client_id < payments.client_id
REF: payments_code.code_id < payments.code_id
