// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs


TABLE clients{
  client_id INT [primary key]
  name_client VARCHAR(50)
  INN VARCHAR(12)
  status_id INT 
}

TABLE payments_code{
  code_id INT [primary key]
  code_name VARCHAR(20)
  code_description VARCHAR(100)
  category VARCHAR(10)
}

TABLE payments{
  payment_id INT [primary key]
  client_id INT
  code_id INT 
  amount DECIMAL(10, 2)
  time_payment TIMESTAMP
}
TABLE clients_status{
  status_id INT [primary key]
  name_status VARCHAR(20)
  code_id INT
}
REF: clients.client_id < payments.client_id
REF: payments_code.code_id < payments.code_id
REF: clients_status.status_id < clients.status_id
REF: payments_code.code_id < clients_status.code_id
